[package]
name = "aoc19"
version = "0.1.0"
authors = ["Akshay Gupta <kitallis@gmail.com>"]
edition = "2018"
default-run = "2019_day1"

[dependencies]

[[bin]]
name = "2019_day1"
path = "2019/src/day1.rs"

[[bin]]
name = "2019_day2"
path = "2019/src/day2.rs"
